import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:honoo/Utility/honoo_colors.dart';
import 'package:honoo/Widgets/honoo_standard_page.dart';
import 'package:honoo/Widgets/section_text.dart';

class BandoHonooFrancolisePage extends StatelessWidget {
  const BandoHonooFrancolisePage({super.key});

  static const String bandoText =
      'Bando honoo\n'
      'per Francolise\n\n'
      'Ho proposto\n'
      'al Comune di Francolise\n'
      'di partecipare\n'
      'al Bando Cultura\n'
      'nei piccoli comuni\n'
      'con un progetto\n'
      'costruito\n'
      'insieme ad honoo\n\n'
      'Si tratta di un bando\n'
      'che si propone\n'
      'di valorizzare\n'
      'e promuovere\n'
      'progetti culturali\n'
      'nei comuni\n'
      'con meno di\n'
      '25.000 abitanti\n\n'
      'La scadenza\n'
      'per la partecipazione\n'
      'è alle ore 12.00\n'
      'del 31 agosto 2026\n\n'
      'Francolise\n'
      'è in provincia di Caserta,\n'
      'sulla via Appia\n\n'
      'È detta La Torre,\n'
      'per il suo castello medievale\n\n'
      'A Francolise ci sono\n'
      'i resti di due ville romane,\n'
      'e poche centinaia di abitanti,\n'
      'perché la maggior parte\n'
      'dei 4.618 abitanti\n'
      'attribuiti a Francolise\n'
      'abita\n'
      'a vari chilometri di distanza\n'
      'dalla Torre,\n'
      'a Sant’Andrea del Pizzone\n\n'
      'Ho pensato\n'
      'di proporre\n'
      'per il bando\n'
      'un progetto coerente\n'
      'con i valori di honoo\n\n'
      'Vorrei\n'
      'includere nel progetto\n'
      'una festa di honoo\n\n'
      'E poi la performance\n'
      'Isola delle Storie,\n'
      'che è stata presentata\n'
      'alla Triennale di Milano\n'
      'nel 2025\n\n'
      'E un concorso fotografico\n\n'
      'E un concorso\n'
      'di honoo,\n'
      'di hinoo\n'
      'e di henoo,\n'
      'realizzati da questo sito,\n'
      'e poi stampati\n'
      'ed esposti\n'
      'in mostra\n\n'
      'Ho pensato\n'
      'ai temi per i concorsi\n\n'
      'Li vuoi conoscere\n'
      'in anticipo,\n'
      'così mi dici\n'
      'che ne pensi?\n\n'
      'Poi vorrei\n'
      'inserire nel progetto\n'
      'un laboratorio\n'
      'sulla creazione\n'
      'di animazioni\n\n'
      'Durante il laboratorio\n'
      'i miei amici di Crocopie\n'
      'realizzeranno\n'
      'le animazioni\n'
      'di honoo.it\n\n'
      'E poi vorrei proporre\n'
      'un laboratorio\n'
      'sulla creazione di suoni\n'
      'per videogiochi e webapp\n\n'
      'Nel corso del laboratorio\n'
      'Umberto Palazzo\n'
      'realizzerà\n'
      'i suoni\n'
      'di honoo.it\n\n'
      'E poi vorrei\n'
      'un altro laboratorio,\n'
      'in cui Alessandro Molina\n'
      'insegnerà ad utilizzare\n'
      'Behavior-Driven Development\n'
      'e\n'
      'Gherkin\n'
      'per creare prodotti digitali\n\n'
      'E poi vorrei\n'
      'incontri\n'
      'con artisti visuali,\n'
      'con fotografi,\n'
      'con musicisti,\n'
      'con autori di testi,\n'
      'secondo lo schema\n'
      'degli Incontri\n'
      'che ho raccontato\n'
      'nella sezione\n'
      'La Banda:\n'
      'condivisione\n'
      'e\n'
      'autoaiuto fra artisti\n\n'
      'Per quanto riguarda\n'
      'le persone\n'
      'che vorrei coinvolgere,\n'
      'come artisti visuali\n'
      'ho pensato\n'
      'ad Antonio Della Guardia,\n'
      'già impegnato con me\n'
      'e con Sira Sebastianelli\n'
      'nella performance\n'
      'Isola delle Storie,\n'
      'a Gabriele Ottino\n'
      'e a Donato Canosa\n\n'
      'Come fotografi\n'
      'ho pensato\n'
      'a Fabio Donato,\n'
      'ad Antonio Biasucci,\n'
      'a Luca Cacciapuoti (Arsenyco),\n'
      'e a Giovanni Vanacore (Feritoie)\n\n'
      'Come musicisti\n'
      'ho pensato\n'
      'ad Umberto Palazzo,\n'
      'a Tamango\n'
      'e a Niccolò Bosio\n\n'
      'Per quanto riguarda\n'
      'gli autori di testi,\n'
      'mi piacerebbe\n'
      'portare la mia testimonianza,\n'
      'in compagnia di Bruno Tognolini\n\n'
      'E poi ho pensato\n'
      'a quattro concerti,\n'
      'perché un progetto come questo\n'
      'senza gente che balla\n'
      'mi mette tristezza\n\n'
      'Per i primi due concerti\n'
      'sicuramente\n'
      'Umberto Palazzo\n'
      'e il Santo Niente\n'
      'e\n'
      'Gerardo Amarante\n\n'
      'Per il terzo concerto\n'
      'vorrei un gruppo\n'
      'di musica popolare\n\n'
      'Sul quarto concerto\n'
      'vorrei riflettere\n'
      'ancora un po’\n\n'
      'Vuoi partecipare\n'
      'al Bando di honoo\n'
      'per Francolise\n'
      'come artista,\n'
      'portando una tua proposta?\n\n'
      'Vuoi partecipare\n'
      'all’organizzazione\n'
      'degli eventi?\n\n'
      'Hai voglia\n'
      'di dare il tuo contributo\n'
      'alla festa di honoo\n'
      'con Vincenzo Antonio Grillo (Ralph)\n'
      'e Antonio Petrillo,\n'
      'nella Stanza del Grafico?\n\n'
      'O ti sentiresti\n'
      'più a tuo agio\n'
      'nell’Angolo del Fotografo,\n'
      'con Luca Cacciapuoti\n'
      '(Arsenyco)\n'
      'e Giovanni Vanacore\n'
      '(Feritoie)?\n\n'
      'O nella Grotta del Poeta,\n'
      'con me e con Bruno Tognolini?\n\n'
      'Vuoi dare una mano\n'
      'alla Vasca dei Messaggi?\n\n'
      'O al Tavolo del Nim?\n\n'
      'Sai che fare\n'
      'l’arbitro di Nim\n'
      'è molto divertente?\n\n'
      'Preferisci occuparti\n'
      'della Stanza Buia?\n\n'
      'O collaborare\n'
      'nell’Agorà?\n\n'
      'Vuoi partecipare\n'
      'alla documentazione\n'
      'degli eventi?\n\n'
      'Contattami subito,\n'
      'e parliamo\n'
      'di quello che vuoi\n\n'
      'Se vinciamo il Bando,\n'
      'realizziamo il progetto\n'
      'a Francolise,\n'
      'nella parte medievale,\n'
      'nel Castello\n'
      'e negli spazi adiacenti\n\n'
      'Se non vinciamo,\n'
      'il progetto lo facciamo lo stesso\n\n'
      'Sempre a Francolise,\n'
      'sempre nella parte medievale,\n'
      'sempre nel Castello\n'
      'e negli spazi adiacenti,\n'
      'ma il programma\n'
      'potrebbe subire variazioni\n\n'
      'Nei prossimi giorni\n'
      'aggiornerò questa pagina,\n'
      'inserendo\n'
      'correzioni,\n'
      'eventuali nuove adesioni,\n'
      'e i link\n'
      'ai nomi delle persone\n'
      'che ho citato\n\n'
      'Questo è l’aggiornamento\n'
      'di oggi\n'
      'domenica 23 agosto\n\n'
      'Carolina Franco\n'
      'si è offerta\n'
      'di condividere\n'
      'negli Incontri\n'
      'la sua esperienza\n'
      'di musicista\n'
      'e di partecipare\n'
      'al progetto\n'
      'con due concerti\n\n'
      'Questa\n'
      'è la sua descrizione\n'
      'per il primo concerto:\n\n'
      '“riscoperta\n'
      'di canti tradizionali\n'
      'del Mediterraneo”\n\n'
      'Questa\n'
      'è la sua descrizione\n'
      'per il secondo concerto:\n\n'
      '“viaggio\n'
      'sull’accettazione della fine\n'
      'attraverso\n'
      'la dimensione onirica”\n\n'
      'Grazie, Carolina\n\n'
      'Ho inserito\n'
      'le tue proposte\n'
      'nel Bando\n\n'
      'Benvenuta nella Banda\n\n'
      'Giovanni Vanacore\n'
      '(Feritoie)\n'
      'ha proposto\n'
      'un’installazione:\n'
      'tappezzare un muro\n'
      'o un’intera stanza\n'
      'con minuscole fototessere,\n'
      'di 3 x 2 cm,\n'
      'di ognuno\n'
      'degli abitanti\n'
      'di Francolise\n\n'
      'Grazie, Giovanni\n\n'
      'È un’idea\n'
      'che mi piace molto\n\n'
      'L’ho già inserita\n'
      'nel Bando\n\n'
      'Ringrazio\n'
      'Massimiliano Corrente,\n'
      'fotografo di Francolise,\n'
      'che ha accolto\n'
      'il mio invito\n'
      'di fotografare\n'
      'ognuno\n'
      'dei partecipanti\n'
      'al progetto\n\n'
      'La mia idea\n'
      'è questa:\n'
      'allestiamo\n'
      'un set fotografico\n'
      'a Francolise\n'
      'e ognuno\n'
      'potrà scegliere\n'
      'se essere fotografato\n'
      'da solo\n'
      'oppure\n'
      'con il nostro Palombaro\n'
      'o\n'
      'con la nostra Sirena\n\n'
      'e se essere fotografato\n'
      'con i suoi vestiti\n'
      'oppure\n'
      'come Palombaro\n'
      'o\n'
      'come Sirena\n\n'
      'Grazie, Massimiliano\n'
      'Benvenuto nella Banda\n\n'
      'Questo è l’aggiornamento\n'
      'di oggi\n'
      'lunedì 24 agosto\n\n'
      'Oggi alle 12.00\n'
      'io e Angelo Grimaldi\n'
      'abbiamo avuto\n'
      'una videochiamata\n'
      'con il sindaco\n'
      'di Francolise,\n'
      'Saturnino Augusto\n'
      'Di Benedetto,\n'
      'e il pro-sindaco,\n'
      'Stefano D’Alterio\n\n'
      'Sono tutti e due\n'
      'estremamente\n'
      'appassionati\n'
      'e legati\n'
      'al loro territorio\n\n'
      'Parlare di progetti\n'
      'con loro\n'
      'è stato un piacere\n\n'
      'Ti comunico\n'
      'subito\n'
      'i dati importanti\n\n'
      'La scadenza\n'
      'per la presentazione\n'
      'del progetto\n'
      'in piattaforma\n'
      'DGCC,\n'
      'che significa\n'
      'Direzione\n'
      'Generale\n'
      'Creatività\n'
      'Contemporanea,\n'
      'da parte del Comune\n'
      'è alle ore 12.00\n'
      'di lunedì 31 agosto\n\n'
      'Il Comune di Francolise\n'
      'oggi si è registrato\n'
      'sulla piattaforma\n\n'
      'Adesso\n'
      'il Comune di Francolise\n'
      'deve stipulare\n'
      'una convenzione\n'
      'in partenariato\n'
      'con honoo,\n'
      'in qualità di\n'
      'ETS,\n'
      'Ente del Terzo Settore,\n'
      'iscritto al\n'
      'RUNTS,\n'
      'Registro Unico Nazionale\n'
      'del Terzo Settore\n\n'
      'Il nostro progetto\n'
      'deve essere approvato\n'
      'con una delibera comunale\n\n'
      'Ci siamo impegnati\n'
      'a presentare\n'
      'il progetto al Comune\n'
      'entro le 12.00 di dopodomani,\n'
      'mercoledì 26 agosto\n\n'
      'Se vuoi essere inserito\n'
      'nel progetto,\n'
      'per cortesia,\n'
      'contattami\n'
      'il prima possibile,\n'
      'e, in ogni caso,\n'
      'non oltre le ore 20.00\n'
      'di domani,\n'
      'martedì 25 agosto\n\n'
      'Se vuoi partecipare,\n'
      'non preoccuparti\n'
      'dell’aspetto formale:\n'
      'contattami\n'
      'e ne parliamo\n\n'
      'Il periodo\n'
      'in cui realizzeremo\n'
      'il progetto\n'
      'sarà quello\n'
      'delle vacanze di Natale,\n'
      'cioè fra meno\n'
      'di quattro mesi\n\n'
      'Contrariamente\n'
      'all’idea iniziale,\n'
      'di realizzare il progetto\n'
      'solo a La Torre,\n'
      'prenderemo\n'
      'in considerazione\n'
      'anche le località\n'
      'di Sant’Andrea del Pizzone\n'
      'e\n'
      'di Montanaro\n\n'
      'Prenderanno\n'
      'parte al progetto,\n'
      'con esposizioni personali,\n'
      'Angi Cariola\n'
      'e\n'
      'Gregorio Di Raffaele\n\n'
      'Grazie, Angi\n'
      'e\n'
      'grazie, Gregorio\n\n'
      'Ieri ho contattato\n'
      'Mara Robustelli,\n'
      'Claudia Setaro\n'
      'e\n'
      'Alessandro Andreozzi\n\n'
      'E poi ho contattato\n'
      'Rachele Montoro\n'
      'e\n'
      'Imma Rhamely Borrelli,\n'
      'che hanno partecipato\n'
      'con i loro honoo\n'
      'alla Prima Festa di honoo,\n'
      'il 16 marzo 2018\n\n'
      'Appena rispondono\n'
      'alla mia proposta,\n'
      'ti informo\n\n'
      'Sto verificando\n'
      'la fattibilità\n'
      'di una idea:\n'
      'un laboratorio\n'
      'di trampoli.\n\n'
      'Che ne dici?\n\n\n\n'
      'Questo è l’aggiornamento\n'
      'di oggi\n'
      'martedì 25 agosto\n\n'
      'Abbiamo le date\n'
      'per la Seconda Festa\n'
      'di honoo\n\n'
      'È un periodo\n'
      'di un mese,\n'
      'da lunedì 7 dicembre 2026\n'
      'a\n'
      'mercoledì 6 gennaio 2027\n\n'
      'In questo periodo\n'
      'io terrò\n'
      'dodici Incontri,\n'
      'su un percorso\n'
      'di scrittura,\n'
      'che si presenta\n'
      'come l’esplorazione\n'
      'di un’Isola:\n'
      'un viaggio articolato\n'
      'in nove tappe\n'
      'e trenta esercizi\n\n'
      'Nel periodo della Festa\n'
      'presenterò\n'
      'con Antonio della Guardia\n'
      'e Sira Sebastianelli\n'
      'la performance\n'
      'Isola delle Storie,\n'
      'che è stata invitata\n'
      'l’anno scorso\n'
      'alla Triennale di Milano\n\n'
      'Terremo\n'
      'quattro Feste di honoo,\n'
      'quattro Seminari,\n'
      'quattro Concerti,\n'
      'e la discoteca\n'
      'tutte le volte che potremo\n\n'
      'In ogni Festa\n'
      'saranno a disposizione\n'
      'dei partecipanti\n'
      'grafici,\n'
      'fotografi,\n'
      'e scrittori\n\n'
      'Ogni Seminario\n'
      'sarà articolato\n'
      'in tre incontri,\n'
      'tranne quello di Trampoli,\n'
      'che prevede\n'
      'sei incontri\n\n'
      'Il Seminario\n'
      'sull’animazione\n'
      'sarà tenuto\n'
      'da Crocopie\n\n'
      'Il Seminario\n'
      'sugli aspetti\n'
      'creativi e produttivi\n'
      'della musica\n'
      'sarà tenuto\n'
      'da Umberto Palazzo\n\n'
      'Il Seminario\n'
      'sulla Regia\n'
      'degli Agenti AI\n'
      'per la costruzione\n'
      'di prodotti digitali\n'
      'sarà tenuto\n'
      'da Alessandro Molina\n\n'
      'Il Seminario\n'
      'di Trampoli\n'
      'sarà tenuto\n'
      'da Giovanna Todisco\n'
      'e all’inizio\n'
      'ogni partecipante\n'
      'sarà assistito\n'
      'nella costruzione\n'
      'dei suoi trampoli\n\n'
      'Il primo concerto sarà\n'
      'di Tullio Tafuri,\n'
      'che si esibirà con il gruppo\n'
      'di musica popolare\n'
      'Populariaurunca\n\n'
      'Avremo poi\n'
      'il progetto musicale\n'
      'SARAKALĪ,\n'
      'nato dall’incontro fra\n'
      'il polistrumentista\n'
      'Marco Maiolino\n'
      'e la cantante\n'
      'Carolina Franco\n\n'
      'Carolina\n'
      'lo definisce così:\n\n'
      '“un omaggio\n'
      'alla tradizione popolare\n'
      'del Mediterraneo\n'
      'e del Sud Italia,\n'
      'in cui il linguaggio\n'
      'dell’elettronica\n'
      'incontra\n'
      'la teatralità della voce,\n'
      'dando spazio a momenti\n'
      'di improvvisazione radicale”\n\n'
      'Carolina Franco\n'
      'presenterà anche\n'
      'un secondo progetto,\n'
      'che ha definito:\n\n'
      '“viaggio\n'
      'sull’accettazione della fine\n'
      'attraverso\n'
      'la dimensione onirica”\n\n'
      'Avremo in permanenza,\n'
      'per tutto il periodo:\n'
      'la mostra fotografica\n'
      'di Angi Cariola,\n'
      'l\'installazione\n'
      'di Gregorio Di Raffaele,\n'
      'i lavori\n'
      'di Camilla Cimino\n'
      'e l’esposizione\n'
      'di honoo, hinoo ed henoo,\n'
      'che si arricchirà\n'
      'di nuovi elementi\n'
      'giorno dopo giorno\n\n'
      'Avremo incontri con musicisti,\n'
      'fotografi,\n'
      'artisti visuali\n'
      'e scrittori,\n'
      'secondo lo schema\n'
      'che ho raccontato\n'
      'nella sezione\n'
      'La Banda:\n'
      'condivisione\n'
      'e\n'
      'autoaiuto fra artisti\n\n'
      'Massimiliano Corrente,\n'
      'fotografo francolisano,\n'
      'fotograferà\n'
      'tutti gli abitanti\n'
      'di Francolise,\n'
      'e dai suoi scatti\n'
      'realizzeremo\n'
      'le piccole stampe\n'
      'di 3 x 2 cm\n'
      'che serviranno\n'
      'per l’installazione\n'
      'proposta\n'
      'da Giovanni Vanacore,\n'
      'Feritoie\n\n'
      'Massimiliano Corrente\n'
      'fotograferà\n'
      'anche tutti i partecipanti\n'
      'alla Festa di honoo\n'
      'a Francolise,\n'
      'e ognuno\n'
      'potrà scegliere\n'
      'se essere fotografato\n'
      'da solo\n'
      'oppure\n'
      'con il nostro Palombaro\n'
      'o\n'
      'con la nostra Sirena\n\n'
      'e se essere fotografato\n'
      'con i suoi vestiti\n'
      'oppure\n'
      'come Palombaro\n'
      'o\n'
      'come Sirena\n\n'
      'Ringrazio Martina Marino,\n'
      'che ha proposto\n'
      'l’idea di un passaporto\n'
      'da dare a ogni partecipante\n'
      'alla Festa di honoo\n\n'
      'In ogni luogo\n'
      'dove terremo\n'
      'un’attività,\n'
      'sarà disponibile un timbro\n'
      'e chi parteciperà\n'
      'all’attività\n'
      'farà apporre\n'
      'sul suo passaporto\n'
      'il timbro dell’attività svolta\n\n'
      'Se hai attività da proporre,\n'
      'contattami immediatamente,\n'
      'perché ci siamo impegnati\n'
      'a consegnare\n'
      'tutto il progetto entro domani:\n'
      'il Comune ha bisogno\n'
      'di riunirsi\n'
      'per approvare\n'
      'il nostro progetto\n'
      'con una delibera\n\n'
      'Una precisazione:\n'
      'se non vinciamo il bando,\n'
      'io la Festa di honoo\n'
      'la faccio comunque\n\n'
      'Cioè\n'
      'dal 7 dicembre 2026\n'
      'al 6 gennaio 2027\n'
      'faccio comunque\n'
      'i dodici incontri\n'
      'sul percorso di scrittura\n\n'
      'Su questo punto,\n'
      'per chiarire il mio pensiero,\n'
      'voglio dirti che\n'
      'io credo che i soldi\n'
      'siano importanti,\n'
      'e che vadano considerati\n'
      'una conseguenza\n'
      'e non un obiettivo\n\n'
      'E questo lo credo\n'
      'da molto,\n'
      'come potrebbe testimoniare\n'
      'Luca Cacciapuoti,\n'
      'Arsenyco\n\n'
      'Questo è l’aggiornamento\n'
      'di oggi\n'
      'giovedì 27 agosto 2026\n\n'
      'Il progetto di honoo\n'
      'è stato consegnato\n'
      'ieri\n'
      'al Sindaco di Francolise,\n'
      'Saturnino Augusto Di Benedetto,\n'
      'che dovrà approvarlo\n'
      'con una delibera\n\n'
      'Poi il Comune stipulerà\n'
      'con honoo\n'
      'un accordo di partenariato\n\n'
      'A questo punto,\n'
      'Agnese Fiorito\n'
      'e\n'
      'Angelo Grimaldi,\n'
      'cioè la nostra Direzione Scientifica,\n'
      'caricheranno tutti i documenti\n'
      'sulla piattaforma Ministeriale\n'
      'della Direzione Generale\n'
      'Creatività Contemporanea,\n'
      'entro la scadenza\n'
      'delle ore 12.00\n'
      'di lunedì 31 agosto\n\n'
      'Nel progetto\n'
      'abbiamo inserito\n'
      'anche\n'
      'la mostra fotografica\n'
      'di Mara Robustelli;\n'
      'le immagini di moda\n'
      'di Eleonora Cecere;\n'
      'l’Installazione\n'
      'di Beatrice Pinto\n'
      'e il progetto\n'
      'di Giusy Petrone\n\n'
      'Mara non sa ancora\n'
      'che le proporrò\n'
      'di partecipare\n'
      'alla Festa di honoo\n'
      "nell'Angolo del Fotografo,\n"
      'con Luca Cacciapuoti,\n'
      'Arsenyco,\n'
      'e Giovanni Vanacore,\n'
      'Feritoie.\n\n'
      'Ne approfitto per ringraziare\n'
      'Marwa Abouamr\n\n'
      'Hai notato che appena apri\n'
      'honoo.it\n'
      'compare per un secondo\n'
      'una Sirena o un Palombaro?\n\n'
      'Il viso della Sirena\n'
      'è di Marwa Abouamr\n\n'
      'Hai riconosciuto il Palombaro?\n\n'
      'Ho proposto\n'
      'a Song Rouxuan\n'
      'di partecipare\n'
      'al progetto\n'
      'sia come modella,\n'
      'con Giovanni Vanacore,\n'
      'Feritoie,\n'
      'sia come grafica,\n'
      'durante le Feste di honoo\n\n'
      'Vuoi partecipare anche tu\n'
      'alle Feste di honoo\n'
      'nella Stanza del Grafico\n'
      'o\n'
      'nell’Angolo del Fotografo\n'
      'o\n'
      'nella Grotta del Poeta?\n\n'
      'Fatti avanti:\n'
      'presenta la tua candidatura\n\n'
      'Mancano poco più di tre mesi\n'
      'e non è il tempo della timidezza\n\n'
      'Scrivimi\n'
      'a\n'
      'venceslao.cembalo@gmail.com\n'
      'e nell’oggetto della mail\n'
      'metti\n'
      'LA BANDA\n\n'
      'honoo ha bisogno di te\n\n'
      'viva honoo\n'
      'viva la Banda\n\n';

  @override
  Widget build(BuildContext context) {
    final TextStyle bodyStyle = GoogleFonts.arvo(
      color: HonooColor.onBackground,
      fontSize: 18,
      fontWeight: FontWeight.w200,
      height: 1.3,
    );

    return HonooStandardPage(
      contentWidthFactor: 0.45,
      child: SectionText(
        key: const Key('section_text'),
        text: bandoText,
        style: bodyStyle,
      ),
    );
  }
}
